version = 1

[[annotations]]
path = [
    "README.md",
    ".gitignore",
    ".pre-commit-config.yaml",
    "index.html",
    "package-lock.json",
    "package.json",
    "vite.config.ts",
    "*.png"
]
precedence = "override"
SPDX-FileCopyrightText = "2026 Jacques Supcik <jacques@supcik.net>"
SPDX-License-Identifier = "MIT"
